server:
  port: 8083

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luojbin.demo.spring.boot.parent.model
  # datasource
spring:
  datasource:
    data: testData.sql
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://192.168.0.101:6379"
          database: 1
        codec: !<org.redisson.client.codec.StringCodec> {}

  # loyofo
loyofo:
  myapp:
    key: myKeyTest
    value: myValueTest



